---
name: Matterbridge Docker
version: 2024.09.1
slug: matterbridge_docker
description: Matter Bridge Docker
url: https://github.com/clipman/HomeAssistant
homeassistant: 2024.1.0
homeassistant_api: true
host_network: true
image: docker.io/letsfly/matterbridge-docker
init: false
arch:
  - aarch64
  - amd64
  - armv7
webui: http://[HOST]:[PORT:8283]/
map:
  - addon_config:rw
options:
  include_domains: []
  include_patterns: []
  include_labels: ['matterbridge']
  include_platforms: []
  exclude_domains: []
  exclude_patterns: []
  exclude_labels: []
  exclude_platforms: []
  overrides: |
    {
      "domains": {
      },
      "entities": {
      }
    }
schema:
  include_domains:
    - str?
  include_patterns:
    - str?
  include_labels:
    - str?
  include_platforms:
    - str?
  exclude_domains:
    - str?
  exclude_patterns:
    - str?
  exclude_labels:
    - str?
  exclude_platforms:
    - str?
  overrides: str
