name: Hyperion.NG
version: "2.0.16"
slug: hyperionng
description: >
  Hyperion은 Hyperion 프로젝트에서 개발한 오픈 소스 바이어스 또는 앰비언트 조명 구현체입니다.
  이 애드온은 Hyperion 프로젝트에서 지원하거나 승인한 것이 아니며,
  컨테이너의 한계로 인해 하드웨어 캡처 카드나 LED 장치에서 작동하지 않을 수 있습니다.
url: https://hyperion-project.org/
arch:
  - amd64
  - armhf
  - aarch64
startup: application
apparmor: false
boot: auto
ports:
  8090/tcp: 8090
  8092/tcp: null
  19333/tcp: 19333
  19400/tcp: 19400
  19444/tcp: 19444
  19445/tcp: 19445
ports_description:
  8090/tcp: Web Admin
  8092/tcp: SSL Web Admin
  19333/tcp: Boblight Server
  19400/tcp: Google Flatbuffers Receiver
  19444/tcp: JSON-RPC Remote Control
  19445/tcp: Protocol Buffers Server
map:
  - config:rw
options: {}
schema: {}
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
uart: true
usb: true
video: true
gpio: true
devices:
  - /dev/spidev0.0
  - /dev/vchiq
  - /dev/amvideo
  - /dev/fb0
  - /dev/mem
webui: "http://[HOST]:[PORT:8090]"
init: false
