erversion: "1.5.2"
slug: matterbridge
name: Matterbridge Server
description: Populate your Home Assistant instance as Matter Bridge.
url: https://github.com/clipman/HomeAssistant/matterbridge
homeassistant: 2024.1.0
homeassistant_api: true
host_network: true
image: luligu/matterbridge:1.5.2/{arch}
init: false
arch:
  - aarch64
  - amd64
  - armv7
webui: http://[HOST]:[PORT:8283]/
map:
  - addon_config:rw
options:
  include_domains: []
  include_patterns: []
  include_labels: ['matterbridge']
  include_platforms: []
  exclude_domains: []
  exclude_patterns: []
  exclude_labels: []
  exclude_platforms: []
  frontend_port: 8283
  matter_port: 5540
  overrides: |
    {
      "domains": {
      },
      "entities": {
      }
    }
schema:
  include_domains:
    - str?
  include_patterns:
    - str?
  include_labels:
    - str?
  include_platforms:
    - str?
  exclude_domains:
    - str?
  exclude_patterns:
    - str?
  exclude_labels:
    - str?
  exclude_platforms:
    - str?
  frontend_port: int
  matter_port: int
  overrides: str
