name: Matterbridge Server
version: "1.5.4"
slug: matterbridge_server
description: Matterbridge Server addon for Home Assistant
startup: before
boot: auto
network_mode: host
webui: http://[HOST]:[PORT:8283]/
ports:
  8283/tcp: 8283
  5540/tcp: 5540
map:
  - addon_config:rw
volumes:
  - /root/Matterbridge
  - /root/.matterbridge
image: luligu/matterbridge
init: false
options:
  include_domains: []
  include_patterns: []
  include_labels: ['matterbridge']
  include_platforms: []
  exclude_domains: []
  exclude_patterns: []
  exclude_labels: []
  exclude_platforms: []
  frontend_port: 8283
  matter_port: 5540
  overrides: |
    {
      "domains": {
      },
      "entities": {
      }
    }
schema:
  include_domains:
    - str?
  include_patterns:
    - str?
  include_labels:
    - str?
  include_platforms:
    - str?
  exclude_domains:
    - str?
  exclude_patterns:
    - str?
  exclude_labels:
    - str?
  exclude_platforms:
    - str?
  frontend_port: int
  matter_port: int
  overrides: str
