name: Korea Radio
version: 2024.10.1
slug: radio
description: Korea Internet Radio for Home Assistant
url: https://github.com/clipman/HomeAssistant
homeassistant: 2024.1.0
homeassistant_api: true
host_network: true
image: docker.io/letsfly/radio-addon
arch:
  - aarch64
  - amd64
  - armv7
ports:
  "3005/tcp": 3005
webui: "http://[HOST]:[PORT:3005]"
startup: application
boot: auto
audio: true
