name: Korea Internet Radio for Home Assistant
version: 2024.09.1
slug: radio
description: Korea Internet Radio for Home Assistant
arch:
  - aarch64
  - amd64
  - armv7
ports:
  "3005/tcp": 3005
webui: "http://[HOST]:[PORT:3005]"
url: https://github.com/clipman/HomeAssistant
startup: application
boot: auto
audio: true
