---
name: Kocom Call with RS485
version: 2024.03.12
slug: kocom_call
description: Kocom Call for Home Assistant
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/clipman/HomeAssistant
startup: application
boot: auto
uart: true
map:
  - share:rw
options:
  share/kocom_call.cfg 설정파일: true
schema:
  share/kocom_call.cfg 설정파일: bool
